import type { Metadata } from 'next'
import { lora } from '@/app/ui/fonts'
import '@/app/ui/globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>{children}</body>
    </html>
  )
}
