name: Deploy to Digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & deploy
    runs-on: ubuntu-latest
    environment:
      name: links.akfgfragments.com
      url: https://links.akfgfragments.com/?id=73

    steps:
      - name: Chekout the repo
        uses: actions/checkout@v4

      - name: Show repo contents
        run: ls -alR
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      
      - name: Build NextJs app
        run: npm run build

      - name: Install SHH-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
     
      - name: deploy
        run: rsync -ar out ${{ secrets.USER }}@${{ secrets.IP }}:${{ secrets.PATH }}