name: Deploy to Digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & deploy
    runs-on: ubuntu-latest
    environment:
      name: links.akfgfragments.com
      url: https://links.akfgfragments.com/?id=73

    steps:
      - name: Chekout the repo
        uses: actions/checkout@v4

      - name: Show repo contents
        run: ls -alR
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Deploy to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.PATH }}
            git pull
            npm ci
            npm run build
            pm2 restart links